# Generated by Django 4.1.12 on 2023-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_expense', '0002_alter_expense_date_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_of_transaction',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of transaction'),
        ),
    ]
